
spring:
  application:
    name: EmailNotificationMicroservice

  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
      properties:
        spring.json.trusted.packages: "com.artemyakkonen.core"
      group-id: user-events-group

server:
  port: 0

logging:
  level:
    root: info
#    org.springframework.kafka: warn
#    com.artemyakkonen: debug